Vagrant.configure("2") do |config|
    config.vm.define "master" do |master|
        master.vm.box_download_insecure = true
        master.vm.box = "centos/7"
        master.vm.network "private_network", ip: "100.0.0.10"
        master.vm.hostname = "master"
        master.vm.provider "virtualbox" do |v|
            v.name = "master"
            v.memory = 4096
            v.cpus = 2
        end
  	config.vm.provision "shell",
	    inline: "sudo yum -y update"
	config.vm.provision 'shell', reboot: true
        config.vm.provision "shell", path: "./install_k8s.sh"
        config.vm.provision "shell", path: "./etape3.sh"
        config.vm.provision "shell", path: "./install_containerd.sh"
        config.vm.provision "shell", path: "./etape5.sh"
        config.vm.provision "shell", path: "./etape6.sh"
        config.vm.provision "shell", path: "./etape7.sh"
#	config.vm.provision "shell", path: "./getdoker.sh"
    end
#    (1..2).each do |i|
#        config.vm.define "worker0#{i}" do |worker|
#            worker.vm.box_download_insecure = true
#            worker.vm.box = "centos/7"
#            worker.vm.network "private_network", ip: "100.0.0.2#{i}"
#            worker.vm.hostname = "worker0#{i}"
#            worker.vm.provider "virtualbox" do |v|
#                v.name ="worker0#{i}"
#                v.memory = 8192
#                v.cpus = 2
#            end
#	    config.vm.provision 'shell', reboot: true
#            config.vm.provision "shell", path: "./install_k8s.sh"
#       	    config.vm.provision "shell", path: "./etape3.sh"
#            config.vm.provision "shell", path: "./install_containerd.sh"
#            config.vm.provision "shell", path: "./etape5.sh"
#        end
#    end
end

